name: Python package

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@develop
      with:
        repository_name: "testpypi"
        repository_url: "https://test.pypi.org/legacy/"
        repository_username: ${{ secrets.USERNAME }}
        repository_password: ${{ secrets.PASSWORD }}
