# name: Http auth

# on:
#   push:
#     branches: ["master"]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build and publish to pypi
#       uses: JRubics/poetry-publish@poetry_install_options
#       with:
#         python_version: "3.9.13"
#         repository_name: "testpypi"
#         repository_url: "https://test.pypi.org/legacy/"
#         repository_username: ${{ secrets.USERNAME }}
#         repository_password: ${{ secrets.PASSWORD }}
#         plugins: "poetry-dynamic-versioning-plugin"
#         poetry_version: "==1.2"
