name: Options

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v2.1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        repository_name: "testpypi"
        poetry_install_options: "--sync"
        poetry_publish_options: "--dry-run"
        python_version: "3.12.3"
        plugins: "poetry-version-plugin"
        poetry_version: "==1.7"
