# name: Trusted publisher

# on:
#   push:
#     branches: ["master"]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build and publish to pypi
#       uses: JRubics/poetry-publish@poetry_install_options
#       with:
#         repository_name: "testpypi"
#         repository_url: "https://test.pypi.org/legacy/"
